language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t  hello198/reverse-proxy -f ./reverse-proxy/Dockerfile ./reverse-proxy
  - docker build -t  hello198/udagram-frontend -f ./udagram-frontend/Dockerfile ./udagram-frontend
  - docker build -t  hello198/udagram-feed -f ./udagram-feed/Dockerfile ./udagram-feed
  - docker build -t  hello198/udagram-usr -f ./udagram-usr/Dockerfile ./udagram-usr


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hello198/reverse-proxy
  - docker push hello198/udagram-frontend
  - docker push hello198/udagram-feed
  - docker push hello198/udagram-usr

