apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-usr
  name: udagram-usr-svc
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    service: udagram-usr 
