apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-feed
  name: udagram-feed-svc
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    service: udagram-feed 
