# Use NodeJS base image
FROM beevelop/ionic AS ionic

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies by copying
# package.json and package-lock.json
COPY package*.json ./udagram-frontend/

# Install dependencies
RUN npm install 

# Copy app source
COPY . .

RUN  ionic init "udagram frontend" --type "custom" --force

RUN ionic build

## Run
FROM nginx:alpine

#COPY www /usr/share/nginx/html
COPY --from=ionic  /usr/src/app/www /usr/share/nginx/html
